### ISSUE TITLE
[Arbeitspaket] aus Datei eingelesenen String zeilenweise in Array speichern

### ISSUE THREAD

**Issue by HolgerSin** [TeamOfStudents/CTP_01_TableReader#53]
**Betroffene Dateien**

tableReader.js

**Beschreibung des Arbeitspakets**

Der aus Datei der Datei Liste.md eingelesenen String soll zeilenweise in einem Array gespeichert werden, also pro Zeile der Datei soll das Array ein Element vom Typ String haben.

**Zusatzinformationen**

Testweise Ausgabe in der Konsole

**Abhängigkeiten**

depends on #32 

### Wichtig
Bitte den im Wiki beschriebenen [Workflow](https://github.com/ComcaveTeamwork/CTP_01_TableReader/wiki/Workflow) einhalten

**Comment by HolgerSin** [comment]
:hourglass_flowing_sand: Alright! Looks like we need to wait for some *dependencies*:

* ComcaveTeamwork/CTP_01_TableReader#32

:bulb: Don't worry, I will continue watching the list above and keep this comment updated. To add or remove a dependency please update this issue/PR description.

Brought to you by **[Dependent Issues](https://github.com/z0al/dependent-issues)** (:robot: ). Happy coding!

**Comment by mauricekoenig** [comment]
Würde mich der Sache annehmen, wenn ansonsten kein Interesse besteht.

**Comment by HolgerSin** [comment]
Ok, ich weise dich mal zu, wir können morgen nachdem das feature 32 auf main gemerged ist nochmal in der Runde fragen ob sich jemand anderes parallel daran versuchen will. Basic String operation wäre für alle eine gute Übung für alle

**Comment by HolgerSin** [comment]
:tada: Great news! Looks like all the *dependencies* have been resolved:

* ~~ComcaveTeamwork/CTP_01_TableReader#32~~

:bulb: To add or remove a dependency please update this issue/PR description.

Brought to you by **[Dependent Issues](https://github.com/z0al/dependent-issues)** (:robot: ). Happy coding!

**Comment by danjan09** [comment]
Assigned im Auftrag von Holger :D

**Comment by HolgerSin** [comment]
:tada: Great news! Looks like all the *dependencies* have been resolved:

* ~~TeamOfStudents/CTP_01_TableReader#32~~

:bulb: To add or remove a dependency please update this issue/PR description.

Brought to you by **[Dependent Issues](https://github.com/z0al/dependent-issues)** (:robot: ). Happy coding!
