### ISSUE TITLE
[Bug] Display List not working correctly

### ISSUE THREAD

**Issue by HolgerSin** [TeamOfStudents/CTP_01_TableReader#89]
**Describe the bug**
The list views after clicking on "display List" do not contain one entry per line, but appear to be one line with automatic word wrap.

**Expected behavior**
The resulting lists should contain one line per person

**Screenshots**
![image](https://user-images.githubusercontent.com/86824184/138667309-a9ff0596-41c9-495d-b81b-4746bc5f45b1.png)

**Comment by nicopape** [comment]
Fixed!

![image](https://user-images.githubusercontent.com/87124169/139946960-f5ce7757-b08b-4045-aea9-4260dc4ec335.png)
